### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by adampenn** [kreuzerk/replace-json-property#15]
How would I go about adding this to my local machine or repo so that I could use it.

I am following your guide on how to set up a npm angular package and am stuck at using this tool.

https://blog.angularindepth.com/the-ultimate-guide-to-set-up-your-angular-library-project-399d95b63500

**Comment by adampenn** [comment]
I am sorry I found it on npm... whoops, maybe at a link to the readme? I'll close this.

Here is the link for anyone else who needs it.
https://www.npmjs.com/package/replace-json-property

**Comment by kreuzerk** [comment]
Glad you found it 👍
