### ISSUE TITLE
src/options-helper missing in latest release

### ISSUE THREAD

**Issue by patoncrispy** [kreuzerk/replace-json-property#33]
Getting an exception in the latest release caused by this line: https://github.com/kreuzerk/replace-json-property/blob/master/bin/replace-json-property.bin.js#L5

The exception is:
```
Error: Cannot find module '../src/options-helper'
```

which occurs in `bin/replace-json-property.bin.js`.

**Comment by kreuzerk** [comment]
@patoncrispy thx a lot for bringing this up. This should be fixed in version `1.6.1`
